backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  - label: "Posts"
    name: "posts"
    files:
      - label: "Posts JSON"
        name: "posts_json"
        file: "posts.json"
        format: "json"           # ensures JSON read/write
        editor:
          preview: false
        fields:
          - label: "Posts"
            name: "posts"
            widget: "list"
            collapsed: true
            summary: "{{fields.title}} — {{fields.date}}"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
              - { label: "Category", name: "category", widget: "select", options: ["music","fashion","events","discourse"] }
              - { label: "Cover URL", name: "cover", widget: "string", required: false }
              - { label: "Excerpt", name: "excerpt", widget: "text" }
              - { label: "Body (HTML or Markdown)", name: "body", widget: "markdown" }
              - { label: "URL (optional, external)", name: "url", widget: "string", required: false }
