backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

site_url: https://<your-netlify-site>.netlify.app

# A single JSON file with a list of posts
collections:
  - label: "Blog"
    name: "blog"
    files:
      - label: "Posts"
        name: "posts"
        file: "posts.json"
        format: "json"
        fields:
          - label: "Posts"
            name: "posts"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
              - { label: "Category", name: "category", widget: "select", options: ["fashion","music","events","discourse"] }
              - { label: "Cover Image URL", name: "cover", widget: "string", required: false }
              - { label: "Excerpt", name: "excerpt", widget: "text" }
              - { label: "Body (HTML)", name: "body", widget: "markdown" }
              - { label: "External URL (optional)", name: "url", widget: "string", required: false }
