backend:
  name: git-gateway
  branch: main

media_folder: "uploads"          # where images get uploaded in the repo
public_folder: "/uploads"        # how the site references them

publish_mode: editorial_workflow # optional, gives “Draft/Review/Publish” states

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    format: "json"
    delete: true
    files:
      - file: "posts.json"
        label: "All Posts"
        name: "posts_json"
        fields:
          - label: "Posts"
            name: "posts"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Date", name: "date", widget: "datetime"}
              - {label: "Category", name: "category", widget: "select", options: ["music","fashion","events","discourse"]}
              - {label: "Cover", name: "cover", widget: "image", required: false}
              - {label: "Excerpt", name: "excerpt", widget: "text", required: false}
              - {label: "Body (HTML ok)", name: "body", widget: "text", required: false}
              - {label: "URL (optional – external full post)", name: "url", widget: "string", required: false}
